replicaCount: 1

image:
  repository: timurbabs/php
  tag: v5
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

postgresql:
  architecture: replication

  auth:
    username: root
    password: root
    database: blacklistdb
    replicationUsername: repl_user
    replicationPassword: repl_password

  primary:
    initdb:
      scripts:
        table.sql: |
          CREATE TABLE blacklisted (
              ip CHAR(15),
              date_ip DATE,
              PRIMARY KEY (ip)
          );

  readReplicas:
    replicaCount: 1
