apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app: php

